#!../../../perl -w

#
# Purpose:
#	To demonstrate the Perl5 Cdk Entry Widget.

#
# Load in the Cdk Extension.
#
use Cdk;
Cdk::init();

# Create a new entry object.
my $entry = new Cdk::Entry ('Label' => "Type Anything:",
				'Width' => 20,
				'Min' => 0,
				'Max' => 256);

# Activate the object.
my $info = $entry->activate();

# Exit Cdk.
Cdk::end();

# Print out the results.
print "\n\n\n\n";
print "You typed: <$info>\n";
