#!../../../perl -w

#
# Purpose:
#	To demonstrate the Perl5 Cdk Scroll Widget

#
# Initialize Cdk.
#
use Cdk;
Cdk::init();

# Set up the scrolling list.
@listItems = ("Item 1", "Item 2", "Item 3",
		"Item 4", "Item 5", "Item 6",
		"Item 7", "Item 8", "Item 9");

# Create the scrolling list object.
my $scroll = new Cdk::Scroll ('Title' => "<C></U/5>Scroll Title",
				'Height' => 6,
				'Width' => 15,
				'Numbers' => "TRUE",
				'List' => \@listItems);

# Activate the scrolling list.
my $itemPicked = $scroll->activate ();

# Exit Cdk.
Cdk::end();

# Print out the info.
print "\n\n\n";
print "Item Picked: $listItems[$itemPicked] \n";
