#!../../../perl -w

#
# Purpose:
#	To demonstrate the Perl5 Cdk Template Widget.

#
# Initialize Cdk.
#
use Cdk;
Cdk::init();

# Create the template object.
my $template = new Cdk::Template ('Label' => 'Type in a date:',
					'Plate' => '## ## ####',
					'Overlay' => 'DD-MM-YYYY');

# Activate the widget.
my $date = $template->activate();

# Get the mixed date back.
my $mixedDate = $template->mix();

# Exit Cdk.
Cdk::end();

# Print out the info.
print "\n\n\n";
print "Without Overlay Mixing: $date\n";
print "With Overlay Mixing   : $mixedDate\n";
